/-
Copyright (c) 2024-2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tobias Rothmann
-/
module

public import ArkLib.Data.Lattices.CyclotomicRing.Core.Modulus
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The Cyclotomic Ring `R[X] / (Φ_m)`

This file builds the cyclotomic ring on top of CompPoly's computable polynomial
type `CompPoly.CPolynomial R`, given a `CyclotomicModulus R` (see
`ArkLib.Data.Lattices.CyclotomicRing.Core.Modulus`).

It is split into two layers, bridged by a single ring homomorphism:

* **Semantic layer** (proof-facing, noncomputable): `Φ.CyclotomicRing`, the
  Mathlib quotient `Polynomial R ⧸ (φ)`. It inherits `CommRing` for free and is
  the genuine cyclotomic ring `R[X] / (Φ_m)` (`cyclotomicRing_eq`).
* **Computable layer**: ring elements are `CPolynomial R`, reduced modulo `φ`
  via CompPoly's `modByMonic` (`Φ.reduce`); multiplication is reduce-after-mul
  for now.

The bridge `Φ.quotientHom : CPolynomial R →+* Φ.CyclotomicRing` is the
composite of CompPoly's `toPoly` ring isomorphism with `Ideal.Quotient.mk`.
Because both are ring homomorphisms, soundness of every computable operation is
just `map_add` / `map_mul` / … — no per-operation soundness axiom is needed.
The only extra fact is `quotientHom_reduce`: reduction modulo
`φ` is invisible in the quotient.

## Main definitions

* `CyclotomicModulus.CyclotomicRing` — the semantic ring `R[X] / (φ)`.
* `CyclotomicModulus.reduce` — computable reduction `· %ₘ φ` on `CPolynomial R`.
* `CyclotomicModulus.mul` — computable multiplication `reduce (a * b)`.
* `CyclotomicModulus.quotientHom` — the soundness bridge `RingHom`.

## Main results

* `cyclotomicRing_eq` — the semantic ring is `Polynomial R ⧸ (cyclotomic m R)`.
* `quotientHom_reduce` — `quotientHom (reduce p) = quotientHom p`.
* `quotientHom_mul` — `quotientHom (mul a b) = quotientHom a * quotientHom b`.
-/

@[expose] public section

open Polynomial CompPoly CompPoly.CPolynomial

namespace ArkLib.Lattices.CyclotomicModulus

variable {R : Type*} [Field R] [BEq R] [LawfulBEq R] (Φ : CyclotomicModulus R)

/-- The ideal `(φ)` generated by the modulus inside `R[X]`. -/
noncomputable def modIdeal : Ideal (Polynomial R) := Ideal.span {Φ.φ.toPoly}

/-- The semantic cyclotomic ring `R[X] / (φ)`. As `φ` is the `Φ.conductor`-th
cyclotomic polynomial (`cyclotomicRing_eq`), this is the cyclotomic ring
`R[X] / (Φ_m)`. It is `CommRing` via `Ideal.Quotient.commRing`. -/
abbrev CyclotomicRing : Type _ := Polynomial R ⧸ Φ.modIdeal

/-- The semantic ring is the genuine cyclotomic ring `R[X] / (Φ_m)`. -/
theorem cyclotomicRing_eq [IsCyclotomic Φ] :
    Φ.CyclotomicRing = (Polynomial R ⧸ Ideal.span {Polynomial.cyclotomic Φ.conductor R}) := by
  rw [CyclotomicRing, modIdeal, IsCyclotomic.isCyclotomic (Φ := Φ)]

/-- Computable reduction of a polynomial modulo the cyclotomic modulus `φ`,
implemented by CompPoly's `modByMonic`. -/
def reduce (p : CPolynomial R) : CPolynomial R := p.modByMonic Φ.φ

/-- Computable multiplication in the cyclotomic ring: multiply in `CPolynomial R`,
then reduce modulo `φ`.

TODO add proper NTT multiplication here, not just reduce-after-CPolynomial-mul
(or prove equivalence to the NTT-based definition once we have the NTT).
Can we adapt CompPoly NTT for this?
-/
def mul (a b : CPolynomial R) : CPolynomial R := Φ.reduce (a * b)

/-- The soundness bridge: send a computable polynomial to the semantic
cyclotomic ring by mapping it to a Mathlib polynomial (`toPoly`, a ring
isomorphism) and then into the quotient. This is a single `RingHom.comp`, so all
operation-soundness facts follow from `map_*`. -/
noncomputable def quotientHom : CPolynomial R →+* Φ.CyclotomicRing :=
  (Ideal.Quotient.mk Φ.modIdeal).comp
    (CPolynomial.ringEquiv : CPolynomial R ≃+* Polynomial R).toRingHom

@[simp] theorem quotientHom_apply (p : CPolynomial R) :
    Φ.quotientHom p = Ideal.Quotient.mk Φ.modIdeal p.toPoly := by
  simp [quotientHom]

/-- Reduction modulo `φ` is invisible in the quotient: `reduce p ≡ p (mod φ)`.
This is the cyclotomic analogue of the `NegacyclicRingSemantics` soundness data. -/
@[simp] theorem quotientHom_reduce [IsCyclotomic Φ] (p : CPolynomial R) :
    Φ.quotientHom (Φ.reduce p) = Φ.quotientHom p := by
  rw [quotientHom_apply, quotientHom_apply, reduce,
    CPolynomial.toPoly_modByMonic _ _ (IsCyclotomic.monic (Φ := Φ)), Ideal.Quotient.eq]
  have h : p.toPoly %ₘ Φ.φ.toPoly - p.toPoly
      = -(Φ.φ.toPoly * (p.toPoly /ₘ Φ.φ.toPoly)) := by
    rw [Polynomial.modByMonic_eq_sub_mul_div]; ring
  rw [h, modIdeal]
  exact neg_mem (Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _))

/-- Multiplication soundness: the computable `mul` maps to the product in the
semantic ring. -/
@[simp] theorem quotientHom_mul [IsCyclotomic Φ] (a b : CPolynomial R) :
    Φ.quotientHom (Φ.mul a b) = Φ.quotientHom a * Φ.quotientHom b := by
  rw [mul, quotientHom_reduce, map_mul]

@[simp] theorem quotientHom_add (a b : CPolynomial R) :
    Φ.quotientHom (a + b) = Φ.quotientHom a + Φ.quotientHom b := map_add _ _ _

@[simp] theorem quotientHom_sub (a b : CPolynomial R) :
    Φ.quotientHom (a - b) = Φ.quotientHom a - Φ.quotientHom b := map_sub _ _ _

@[simp] theorem quotientHom_neg (a : CPolynomial R) :
    Φ.quotientHom (-a) = -Φ.quotientHom a := map_neg _ _

@[simp] theorem quotientHom_zero : Φ.quotientHom 0 = 0 := map_zero _

@[simp] theorem quotientHom_one : Φ.quotientHom 1 = 1 := map_one _

/-- The modulus itself vanishes in the quotient — the defining relation of `R[X] / (φ)`. -/
@[simp] theorem quotientHom_phi : Φ.quotientHom Φ.φ = 0 := by
  rw [quotientHom_apply]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)

end ArkLib.Lattices.CyclotomicModulus
