/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.RingTheory.Ideal.Operations

/-!
# First-order Taylor congruences for multivariate polynomials

This file gives an ideal-theoretic first-order Taylor formula for multivariate polynomials.
If every coordinate of a finitely supported perturbation `d` belongs to an ideal `I`, then
evaluating at `a + d` agrees modulo `I ^ 2` with evaluating at `a` and adding the formal
partial-derivative terms.

This is the multivariate linearization used in the proof of [Kop15, Theorem 4.4]: there the
coordinates are a polynomial and its formal derivatives, and `I` is generated by a power of
`T - alpha`. The theorem below isolates only the Taylor step that makes all terms of order at
least two vanish. It does not prove the one-step differential-equation lift or the recursive
solution-counting result of [Kop15, Corollary 4.5].

## References

* [Kopparty, S., *List-Decoding Multiplicity Codes*][Kop15]
-/

namespace MvPolynomial

open scoped BigOperators

noncomputable section

variable {R S σ : Type*} [CommRing R] [CommRing S]

/-- The linear term in the change of `p` under a perturbation `d`, evaluated at `a`.

The finite set `s` describes the support of `d`. It may contain variables not occurring in `p`;
their partial derivatives simply contribute zero. -/
def firstOrderIncrement (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (p : MvPolynomial σ R) : S :=
  ∑ i ∈ s, eval₂Hom f a (pderiv i p) * d i

/-- The first-order increment is additive in the polynomial. -/
theorem firstOrderIncrement_add (f : R →+* S) (a d : σ → S) (s : Finset σ)
    (p q : MvPolynomial σ R) :
    firstOrderIncrement f a d s (p + q) =
      firstOrderIncrement f a d s p + firstOrderIncrement f a d s q := by
  simp [firstOrderIncrement, add_mul, Finset.sum_add_distrib]

/-- A finitely supported perturbation changes a multivariate polynomial by its formal linear
term modulo the square of any ideal containing the perturbation coordinates.

This is a ring-theoretic Taylor congruence: no field, characteristic, or degree hypothesis is
needed. The support hypotheses say exactly that `d` vanishes outside `s` and lies in `I` on `s`.
The conclusion keeps the quadratic error as ideal membership, so consumers can specialize `I`
to a principal ideal generated by a power of a polynomial. -/
theorem eval₂Hom_add_sub_firstOrderIncrement_mem_sq (f : R →+* S) (a d : σ → S)
    (s : Finset σ) (I : Ideal S) (p : MvPolynomial σ R)
    (hd : ∀ i ∈ s, d i ∈ I) (hd_zero : ∀ i, i ∉ s → d i = 0) :
    eval₂Hom f (a + d) p - eval₂Hom f a p - firstOrderIncrement f a d s p ∈ I ^ 2 := by
  classical
  have hd_all (i : σ) : d i ∈ I := by
    by_cases hi : i ∈ s
    · exact hd i hi
    · simp [hd_zero i hi]
  induction p using MvPolynomial.induction_on with
  | C c => simp [firstOrderIncrement]
  | add p q hp hq =>
      simpa [firstOrderIncrement_add, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
        (I ^ 2).add_mem hp hq
  | mul_X p n hp =>
      have hlinear : firstOrderIncrement f a d s p ∈ I := by
        apply I.sum_mem
        intro i hi
        exact I.mul_mem_left _ (hd_all i)
      have hquadratic : firstOrderIncrement f a d s p * d n ∈ I ^ 2 := by
        rw [pow_two]
        exact Ideal.mul_mem_mul hlinear (hd_all n)
      have hmain :
          (eval₂Hom f (a + d) p - eval₂Hom f a p - firstOrderIncrement f a d s p) *
              (a n + d n) + firstOrderIncrement f a d s p * d n ∈ I ^ 2 :=
        (I ^ 2).add_mem ((I ^ 2).mul_mem_right _ hp) hquadratic
      have hsingle :
          ∑ i ∈ s,
              eval₂Hom f a p * eval₂Hom f a (if n = i then 1 else 0) * d i =
            eval₂Hom f a p * d n := by
        by_cases hn : n ∈ s
        · rw [Finset.sum_eq_single n]
          · simp
          · intro i hi hin
            simp [hin.symm]
          · simp [hn]
        · rw [Finset.sum_eq_zero]
          · simp [hd_zero n hn]
          · intro i hi
            have hni : n ≠ i := by
              intro h
              subst i
              exact hn hi
            simp [hni]
      have hmul :
          firstOrderIncrement f a d s (p * X n) =
            firstOrderIncrement f a d s p * a n + eval₂Hom f a p * d n := by
        rw [firstOrderIncrement]
        simp only [MvPolynomial.pderiv_mul, map_add, map_mul, eval₂Hom_X',
          MvPolynomial.pderiv_X, Pi.single_apply, add_mul, Finset.sum_add_distrib]
        rw [hsingle]
        simp only [firstOrderIncrement]
        congr 1
        rw [Finset.sum_mul]
        apply Finset.sum_congr rfl
        intro i hi
        ring
      simp only [map_mul, eval₂Hom_X', Pi.add_apply, hmul]
      convert hmain using 1
      ring

/-- For finitely many variables, the support set can be taken to be all variables. -/
theorem eval₂Hom_add_sub_firstOrderIncrement_univ_mem_sq [Fintype σ]
    (f : R →+* S) (a d : σ → S) (I : Ideal S) (p : MvPolynomial σ R)
    (hd : ∀ i, d i ∈ I) :
    eval₂Hom f (a + d) p - eval₂Hom f a p -
        firstOrderIncrement f a d Finset.univ p ∈ I ^ 2 := by
  apply eval₂Hom_add_sub_firstOrderIncrement_mem_sq f a d Finset.univ I p
  · simpa using hd
  · simp

/-- If every perturbation coordinate is divisible by `u ^ k`, the Taylor error is divisible by
`u ^ (k + 1)` for positive `k`.

The ideal-square theorem actually gives divisibility by `(u ^ k) ^ 2`; this corollary weakens it
to the next power, matching the modulus transition in [Kop15, Theorem 4.4]. -/
theorem pow_succ_dvd_eval₂Hom_add_sub_firstOrderIncrement (f : R →+* S) (a d : σ → S)
    (s : Finset σ) (p : MvPolynomial σ R) (u : S) (k : ℕ) (hk : 0 < k)
    (hd : ∀ i ∈ s, u ^ k ∣ d i) (hd_zero : ∀ i, i ∉ s → d i = 0) :
    u ^ (k + 1) ∣
      eval₂Hom f (a + d) p - eval₂Hom f a p - firstOrderIncrement f a d s p := by
  have hmem := eval₂Hom_add_sub_firstOrderIncrement_mem_sq f a d s
    (Ideal.span {u ^ k}) p (fun i hi ↦ Ideal.mem_span_singleton.mpr (hd i hi)) hd_zero
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hmem
  exact (pow_dvd_pow u (by omega : k + 1 ≤ k * 2)).trans (by simpa [pow_mul] using hmem)

end

end MvPolynomial
