/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import ArkLib.ToMathlib.AlgebraicGeometry.PrincipalOpen.Dimension
import Mathlib.LinearAlgebra.Vandermonde

/-!
# Dimension from partial polynomial evaluations

The first `c` coefficients of a polynomial are determined by its values at `c` distinct points
once the remaining coefficients are retained.  This first bounds the ordinary coefficient
quotient using one challenge generator and `k - c` remaining coefficient generators.  Only then
does the application localize at a pulled-back separant; the explicit away presentation shows
that adjoining its constrained inverse does not increase dimension.
-/

noncomputable section

open MvPolynomial Matrix

namespace AffineHilbert

variable {F A σ : Type*} [Field F]

/-- Vandermonde recovery remains valid inside an arbitrary commutative `F`-algebra: if all `c`
evaluations of `c` coefficients belong to a subalgebra, then each coefficient does too. -/
theorem coeff_mem_subalgebra_of_vandermonde_evaluations
    [CommRing A] [Algebra F A] (B : Subalgebra F A) {c : ℕ}
    (α : Fin c ↪ F) (a : Fin c → A)
    (heval : ∀ i, ∑ j, algebraMap F A (α i ^ j.val) * a j ∈ B) :
    ∀ j, a j ∈ B := by
  classical
  let V : Matrix (Fin c) (Fin c) F := Matrix.vandermonde α
  have hdet : V.det ≠ 0 := Matrix.det_vandermonde_ne_zero_iff.mpr α.injective
  let _ : Invertible V := Matrix.invertibleOfIsUnitDet V (isUnit_iff_ne_zero.mpr hdet)
  let y : Fin c → A := fun i ↦ ∑ j, algebraMap F A (V i j) * a j
  have hy : ∀ i, y i ∈ B := by
    intro i
    simpa only [y, V, Matrix.vandermonde_apply] using heval i
  intro j
  have hrecover : a = (V⁻¹.map (algebraMap F A)).mulVec y := by
    rw [show y = (V.map (algebraMap F A)).mulVec a by
      funext i
      simp only [y, Matrix.mulVec, dotProduct, Matrix.map_apply]]
    rw [Matrix.mulVec_mulVec, ← Matrix.map_mul, Matrix.inv_mul_of_invertible,
      Matrix.map_one, Matrix.one_mulVec]
    · exact map_zero (algebraMap F A)
    · exact map_one (algebraMap F A)
  rw [hrecover]
  change ∑ i, algebraMap F A ((V⁻¹) j i) * y i ∈ B
  exact B.sum_mem fun i _ ↦ B.mul_mem (B.algebraMap_mem ((V⁻¹) j i)) (hy i)

/-- The evaluation equation for a degree-`< k` coefficient vector and one challenge coordinate.
At a point `(z, coeff)`, it reads `∑ l, coeff_l * α^l = received(z)`. -/
def polynomialCoefficientEvaluation (k : ℕ) (α : F) (received : Polynomial F) :
    MvPolynomial (Option (Fin k)) F :=
  (∑ l : Fin k, C (α ^ l.val) * X (some l)) -
    received.eval₂ C (X none)

/-- The affine specialization of `polynomialCoefficientEvaluation`, with received polynomial
`f + X * g`. -/
def affineCoefficientEvaluation (k : ℕ) (α f g : F) :
    MvPolynomial (Option (Fin k)) F :=
  polynomialCoefficientEvaluation k α (Polynomial.C f + Polynomial.X * Polynomial.C g)

/-- Any affine coefficient ideal containing `c` evaluation equations at distinct points has
Hilbert dimension at most `k + 1 - c`.

This is the ordinary quotient-algebra step, before any separant is inverted.  In the quotient,
the evaluation equations and the last `k - c` coefficients recover the first `c` coefficients by
the Vandermonde lemma.  Hence the quotient is generated by the challenge and `k - c` remaining
coefficients. -/
theorem polynomialCoefficientEvaluation_hilbertPolynomial_natDegree_le
    {k c : ℕ} (hck : c ≤ k) (α : Fin c ↪ F) (received : Fin c → Polynomial F)
    {J : Ideal (MvPolynomial (Option (Fin k)) F)} (hJ : J ≠ ⊤)
    (heval : ∀ i, polynomialCoefficientEvaluation k (α i) (received i) ∈ J) :
    (hilbertPolynomial J).natDegree ≤ k + 1 - c := by
  classical
  let A := MvPolynomial (Option (Fin k)) F ⧸ J
  let z : A := Ideal.Quotient.mk J (X none)
  let coeff : Fin k → A := fun l ↦ Ideal.Quotient.mk J (X (some l))
  let B : Subalgebra F A := Algebra.adjoin F
    (insert z (Set.range fun l : Fin (k - c) ↦ coeff ⟨c + l.val, by omega⟩))
  have hsplit (u : Fin k → A) :
      (∑ l : Fin k, u l) =
        (∑ l : Fin c, u ⟨l.val, l.isLt.trans_le hck⟩) +
          ∑ l : Fin (k - c), u ⟨c + l.val, by omega⟩ := by
    let e : Fin (c + (k - c)) ≃ Fin k := finCongr (Nat.add_sub_of_le hck)
    rw [← Equiv.sum_comp e, Fin.sum_univ_add]
    congr 1
  have hfull (i : Fin c) :
      (∑ l : Fin k, algebraMap F A ((α i) ^ l.val) * coeff l) =
        (received i).eval₂ (algebraMap F A) z := by
    have hz : Ideal.Quotient.mk J
        (polynomialCoefficientEvaluation k (α i) (received i)) = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.mpr (heval i)
    have hC (a : F) : Ideal.Quotient.mk J (C a) = algebraMap F A a := by
      rw [← Ideal.Quotient.mk_algebraMap]
      rfl
    have hmap : (Ideal.Quotient.mk J).comp C = algebraMap F A := by
      ext a
      exact hC a
    simpa only [polynomialCoefficientEvaluation, map_sub, map_sum, map_mul,
      Polynomial.hom_eval₂, hmap, hC, sub_eq_zero, z, coeff] using hz
  have hlow : ∀ i, ∑ l : Fin c, algebraMap F A ((α i) ^ l.val) *
      coeff ⟨l.val, l.isLt.trans_le hck⟩ ∈ B := by
    intro i
    let u : Fin k → A := fun l ↦ algebraMap F A ((α i) ^ l.val) * coeff l
    have htail : (∑ l : Fin (k - c), u ⟨c + l.val, by omega⟩) ∈ B := by
      apply B.sum_mem
      intro l _
      apply B.mul_mem (B.algebraMap_mem _)
      apply Algebra.subset_adjoin
      exact Set.mem_insert_iff.mpr (Or.inr ⟨l, rfl⟩)
    have hrhs : (received i).eval₂ (algebraMap F A) z ∈ B := by
      induction received i using Polynomial.induction_on' with
      | add p q hp hq =>
          rw [Polynomial.eval₂_add]
          exact B.add_mem hp hq
      | monomial m a =>
          rw [Polynomial.eval₂_monomial]
          exact B.mul_mem (B.algebraMap_mem _)
            (B.pow_mem (Algebra.subset_adjoin (Set.mem_insert z _)) m)
    have hsum : (∑ l : Fin k, u l) ∈ B := by
      rw [hfull i]
      exact hrhs
    have hdecomp := hsplit u
    rw [hdecomp] at hsum
    simpa only [add_sub_cancel_right] using B.sub_mem hsum htail
  have hlowcoeff : ∀ l : Fin c, coeff ⟨l.val, l.isLt.trans_le hck⟩ ∈ B :=
    coeff_mem_subalgebra_of_vandermonde_evaluations B α
      (fun l ↦ coeff ⟨l.val, l.isLt.trans_le hck⟩) hlow
  have hcoeff : ∀ l, coeff l ∈ B := by
    intro l
    by_cases hl : l.val < c
    · exact hlowcoeff ⟨l.val, hl⟩
    · have hcl : c ≤ l.val := Nat.le_of_not_gt hl
      let j : Fin (k - c) := ⟨l.val - c, by omega⟩
      have hj : c + j.val = l.val := by simp only [j]; omega
      apply Algebra.subset_adjoin
      exact Set.mem_insert_iff.mpr (Or.inr ⟨j, by simp only [hj]⟩)
  have hgenerate : B = ⊤ := by
    apply top_unique
    intro x hx
    clear hx
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    induction p using MvPolynomial.induction_on with
    | C a =>
        change algebraMap F A a ∈ B
        exact B.algebraMap_mem a
    | add p q hp hq =>
        rw [map_add]
        exact B.add_mem hp hq
    | mul_X p l hp =>
        rw [map_mul]
        apply B.mul_mem hp
        cases l with
        | none => exact Algebra.subset_adjoin (Set.mem_insert z _)
        | some l => exact hcoeff l
  let generators : Option (Fin (k - c)) → A
    | none => z
    | some l => coeff ⟨c + l.val, by omega⟩
  have hrange : Set.range generators =
      insert z (Set.range fun l : Fin (k - c) ↦ coeff ⟨c + l.val, by omega⟩) := by
    ext x
    constructor
    · rintro ⟨l, rfl⟩
      cases l with
      | none => exact Set.mem_insert _ _
      | some l => exact Set.mem_insert_iff.mpr (Or.inr ⟨l, rfl⟩)
    · rintro (rfl | ⟨l, rfl⟩)
      · exact ⟨none, rfl⟩
      · exact ⟨some l, rfl⟩
  let evalHom : MvPolynomial (Option (Fin (k - c))) F →ₐ[F] A :=
    MvPolynomial.aeval generators
  have hsurj : Function.Surjective evalHom := by
    change Function.Surjective (MvPolynomial.aeval generators)
    rw [← AlgHom.range_eq_top, ← Algebra.adjoin_range_eq_range_aeval, hrange]
    exact hgenerate
  let quotientEvalHom :
      (MvPolynomial (Option (Fin (k - c))) F ⧸ ⊥) →ₐ[F] A :=
    evalHom.comp (AlgEquiv.quotientBot F _).toAlgHom
  have hquotientSurj : Function.Surjective quotientEvalHom :=
    hsurj.comp (AlgEquiv.quotientBot F _).surjective
  have hdim := hilbertPolynomial_natDegree_le_of_surjective_algHom
    (J := (⊥ : Ideal (MvPolynomial (Option (Fin (k - c))) F)))
    (I := J) quotientEvalHom hquotientSurj hJ
  have hambient := hilbertPolynomial_natDegree_le
    (⊥ : Ideal (MvPolynomial (Option (Fin (k - c))) F))
  rw [Nat.card_eq_fintype_card, Fintype.card_option, Fintype.card_fin] at hambient
  omega

/-- Any affine coefficient ideal containing `c` evaluation equations at distinct points has
Hilbert dimension at most `k + 1 - c`. -/
theorem coefficientEvaluation_hilbertPolynomial_natDegree_le
    {k c : ℕ} (hck : c ≤ k) (α : Fin c ↪ F) (f g : Fin c → F)
    {J : Ideal (MvPolynomial (Option (Fin k)) F)} (hJ : J ≠ ⊤)
    (heval : ∀ i, affineCoefficientEvaluation k (α i) (f i) (g i) ∈ J) :
    (hilbertPolynomial J).natDegree ≤ k + 1 - c := by
  apply polynomialCoefficientEvaluation_hilbertPolynomial_natDegree_le hck α
    (fun i ↦ Polynomial.C (f i) + Polynomial.X * Polynomial.C (g i)) hJ
  intro i
  simpa only [affineCoefficientEvaluation] using heval i

/-- The evaluation equation for an ordinary degree-`< k` coefficient vector.  At a coefficient
point `coeff`, it reads `∑ l, coeff_l * α^l = y`. -/
def fixedCoefficientEvaluation (k : ℕ) (α y : F) : MvPolynomial (Fin k) F :=
  (∑ l : Fin k, C (α ^ l.val) * X l) - C y

/-- Ordinary coefficient evaluations are affine-linear in the coefficient variables. -/
theorem fixedCoefficientEvaluation_totalDegree_le_one (k : ℕ) (α y : F) :
    (fixedCoefficientEvaluation k α y).totalDegree ≤ 1 := by
  classical
  have hsum : (∑ l : Fin k, C (α ^ l.val) * X l : MvPolynomial (Fin k) F).totalDegree ≤ 1 := by
    refine Finset.sum_induction (s := Finset.univ)
      (fun l : Fin k ↦ C (α ^ l.val) * X l)
      (fun p : MvPolynomial (Fin k) F ↦ p.totalDegree ≤ 1) ?_ ?_ ?_
    · intro p q hp hq
      exact (MvPolynomial.totalDegree_add p q).trans (max_le hp hq)
    · simp
    · intro l _
      calc
        (C (α ^ l.val) * X l : MvPolynomial (Fin k) F).totalDegree ≤
            (C (α ^ l.val) : MvPolynomial (Fin k) F).totalDegree +
              (X l : MvPolynomial (Fin k) F).totalDegree :=
          MvPolynomial.totalDegree_mul _ _
        _ = 1 := by rw [MvPolynomial.totalDegree_C, MvPolynomial.totalDegree_X]
  exact (MvPolynomial.totalDegree_sub _ _).trans (max_le hsum (by simp))

/-- Any ordinary coefficient ideal containing `c` evaluations at distinct points has Hilbert
dimension at most `k - c`.

This is the fixed-challenge counterpart of
`coefficientEvaluation_hilbertPolynomial_natDegree_le`.  Vandermonde elimination recovers the
first `c` coefficients from the evaluation equations and the remaining `k - c` coefficients. -/
theorem fixedCoefficientEvaluation_hilbertPolynomial_natDegree_le
    {k c : ℕ} (hck : c ≤ k) (α : Fin c ↪ F) (y : Fin c → F)
    {J : Ideal (MvPolynomial (Fin k) F)} (hJ : J ≠ ⊤)
    (heval : ∀ i, fixedCoefficientEvaluation k (α i) (y i) ∈ J) :
    (hilbertPolynomial J).natDegree ≤ k - c := by
  classical
  let A := MvPolynomial (Fin k) F ⧸ J
  let coeff : Fin k → A := fun l ↦ Ideal.Quotient.mk J (X l)
  let B : Subalgebra F A := Algebra.adjoin F
    (Set.range fun l : Fin (k - c) ↦ coeff ⟨c + l.val, by omega⟩)
  have hsplit (u : Fin k → A) :
      (∑ l : Fin k, u l) =
        (∑ l : Fin c, u ⟨l.val, l.isLt.trans_le hck⟩) +
          ∑ l : Fin (k - c), u ⟨c + l.val, by omega⟩ := by
    let e : Fin (c + (k - c)) ≃ Fin k := finCongr (Nat.add_sub_of_le hck)
    rw [← Equiv.sum_comp e, Fin.sum_univ_add]
    congr 1
  have hfull (i : Fin c) :
      (∑ l : Fin k, algebraMap F A ((α i) ^ l.val) * coeff l) =
        algebraMap F A (y i) := by
    have hz : Ideal.Quotient.mk J
        (fixedCoefficientEvaluation k (α i) (y i)) = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.mpr (heval i)
    have hC (a : F) : Ideal.Quotient.mk J (C a) = algebraMap F A a := by
      rw [← Ideal.Quotient.mk_algebraMap]
      rfl
    simpa only [fixedCoefficientEvaluation, map_sub, map_sum, map_mul, hC,
      sub_eq_zero, coeff] using hz
  have hlow : ∀ i, ∑ l : Fin c, algebraMap F A ((α i) ^ l.val) *
      coeff ⟨l.val, l.isLt.trans_le hck⟩ ∈ B := by
    intro i
    let u : Fin k → A := fun l ↦ algebraMap F A ((α i) ^ l.val) * coeff l
    have htail : (∑ l : Fin (k - c), u ⟨c + l.val, by omega⟩) ∈ B := by
      apply B.sum_mem
      intro l _
      apply B.mul_mem (B.algebraMap_mem _)
      apply Algebra.subset_adjoin
      exact ⟨l, rfl⟩
    have hsum : (∑ l : Fin k, u l) ∈ B := by
      rw [hfull i]
      exact B.algebraMap_mem _
    have hdecomp := hsplit u
    rw [hdecomp] at hsum
    simpa only [add_sub_cancel_right] using B.sub_mem hsum htail
  have hlowcoeff : ∀ l : Fin c, coeff ⟨l.val, l.isLt.trans_le hck⟩ ∈ B :=
    coeff_mem_subalgebra_of_vandermonde_evaluations B α
      (fun l ↦ coeff ⟨l.val, l.isLt.trans_le hck⟩) hlow
  have hcoeff : ∀ l, coeff l ∈ B := by
    intro l
    by_cases hl : l.val < c
    · exact hlowcoeff ⟨l.val, hl⟩
    · have hcl : c ≤ l.val := Nat.le_of_not_gt hl
      let j : Fin (k - c) := ⟨l.val - c, by omega⟩
      have hj : c + j.val = l.val := by simp only [j]; omega
      apply Algebra.subset_adjoin
      exact ⟨j, by simp only [hj]⟩
  have hgenerate : B = ⊤ := by
    apply top_unique
    intro x hx
    clear hx
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    induction p using MvPolynomial.induction_on with
    | C a =>
        change algebraMap F A a ∈ B
        exact B.algebraMap_mem a
    | add p q hp hq =>
        rw [map_add]
        exact B.add_mem hp hq
    | mul_X p l hp =>
        rw [map_mul]
        exact B.mul_mem hp (hcoeff l)
  let generators : Fin (k - c) → A := fun l ↦ coeff ⟨c + l.val, by omega⟩
  let evalHom : MvPolynomial (Fin (k - c)) F →ₐ[F] A :=
    MvPolynomial.aeval generators
  have hsurj : Function.Surjective evalHom := by
    change Function.Surjective (MvPolynomial.aeval generators)
    rw [← AlgHom.range_eq_top, ← Algebra.adjoin_range_eq_range_aeval]
    exact hgenerate
  let quotientEvalHom :
      (MvPolynomial (Fin (k - c)) F ⧸ ⊥) →ₐ[F] A :=
    evalHom.comp (AlgEquiv.quotientBot F _).toAlgHom
  have hquotientSurj : Function.Surjective quotientEvalHom :=
    hsurj.comp (AlgEquiv.quotientBot F _).surjective
  have hdim := hilbertPolynomial_natDegree_le_of_surjective_algHom
    (J := (⊥ : Ideal (MvPolynomial (Fin (k - c)) F)))
    (I := J) quotientEvalHom hquotientSurj hJ
  have hambient := hilbertPolynomial_natDegree_le
    (⊥ : Ideal (MvPolynomial (Fin (k - c)) F))
  rw [Nat.card_eq_fintype_card, Fintype.card_fin] at hambient
  omega

/-- Localized coefficient-quotient form of the partial-evaluation dimension bridge.

Here `J` is the prime evaluation quotient on the challenge and coefficient variables, and `t` is
the separant expressed in those variables.  The source localization maps onto the retained target
localization through `g`.  Thus the inverse of the separant is supplied by localization on both
sides and does not appear as an additional polynomial generator. -/
theorem retainedPrime_hilbertPolynomial_natDegree_le_of_coefficientLocalization
    [Finite σ] {τ : Type*} [Finite τ] {d : ℕ}
    {J : Ideal (MvPolynomial τ F)} (hJ : J.IsPrime)
    {t : MvPolynomial τ F} (ht : t ∉ J)
    (hJdim : (hilbertPolynomial J).natDegree ≤ d)
    {P : Ideal (MvPolynomial σ F)} (hP : P.IsPrime)
    {s : MvPolynomial σ F} (hs : s ∉ P)
    (g : Localization.Away (Ideal.Quotient.mk J t) →ₐ[F]
      Localization.Away (Ideal.Quotient.mk P s))
    (hg : Function.Surjective g) :
    (hilbertPolynomial P).natDegree ≤ d :=
  (hilbertPolynomial_natDegree_le_of_surjective_away_algHom hJ ht hP hs g hg).trans hJdim

end AffineHilbert
