/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import Mathlib.Tactic.NormNum

/-!
# Concrete ProveKit WHIR parameter arithmetic

This module records the two pinned ProveKit WHIR parameter rows generated by
`check_modular_whir.py` in the all-rate Reed--Solomon list-decoding paper repository at source
commit `8804e80e8e890d01bb585f2bd5e5b564ac0fd80d`. The values match
`scripts/examples/modular-whir-beyond-johnson.json` in that repository.

The theorems below certify exact numerical arithmetic used by the checker: the rate and vector-size
identities, the finite Johnson comparison, the changed-slot error bounds, query selection, and
conservative raw-payload lower bounds. They do not prove that these parameters satisfy an ArkLib
list-decoding or coding-soundness theorem. Such a conclusion requires a separate theorem-level
bridge from the concrete certificate to the generic Reed--Solomon development.
-/

namespace ArkLibExamples.ReedSolomon.ProveKit

/-- A pinned row of the ProveKit WHIR parameter calculation. -/
structure Profile where
  /-- Reed--Solomon block length. -/
  n : Nat
  /-- Reed--Solomon dimension. -/
  k : Nat
  /-- Length of the interleaved vector tested by the initial out-of-domain check. -/
  vectorSize : Nat
  /-- Number of field elements in one queried row. -/
  interleavingWidth : Nat
  /-- Number of polynomials batched in this calculation. -/
  batchSize : Nat
  /-- Cardinality of the challenge field. -/
  fieldSize : Nat
  /-- Numerator of the agreement fraction, whose denominator is `n`. -/
  agreementNumerator : Nat
  /-- Multiplicity parameter in the concrete list-decoding certificate. -/
  multiplicity : Nat
  /-- Lower band endpoint in the concrete list-decoding certificate. -/
  bandLower : Nat
  /-- Taylor cutoff in the concrete list-decoding certificate. -/
  taylorCutoff : Nat
  /-- Upper bound for the exceptional challenge count. -/
  exceptionalCount : Nat
  /-- Upper bound for the decoded list size. -/
  listSize : Nat
  /-- Selected number of uniform queries. -/
  queries : Nat
  /-- Number of initial out-of-domain samples. -/
  initialOodSamples : Nat
  /-- Inclusive 64-bit proof-of-work acceptance threshold. -/
  powThreshold : Nat
  /-- Query count in the pinned nominal ProveKit profile. -/
  nominalQueries : Nat
  /-- Auxiliary zero-slack query reference used by the source checker. -/
  zeroSlackQueryReference : Nat
  /-- Encoded bytes per base-field element. -/
  fieldBytes : Nat
  /-- Encoded bytes per extension-field element. -/
  extensionBytes : Nat

/-- The pinned BN254 parameter row. -/
def bn254 : Profile where
  n := 1048576
  k := 262144
  vectorSize := 2097152
  interleavingWidth := 8
  batchSize := 1
  fieldSize := 21888242871839275222246405745257275088548364400416034343698204186575808495617
  agreementNumerator := 492831
  multiplicity := 384
  bandLower := 168
  taylorCutoff := 688
  exceptionalCount := 1126820196482631879700641773
  listSize := 147000408479737
  queries := 109
  initialOodSamples := 1
  powThreshold := 18786624067678312
  nominalQueries := 127
  zeroSlackQueryReference := 119
  fieldBytes := 32
  extensionBytes := 32

/-- The pinned cubic Goldilocks parameter row. -/
def goldilocksCubic : Profile where
  n := 1048576
  k := 262144
  vectorSize := 2097152
  interleavingWidth := 8
  batchSize := 1
  fieldSize := 6277101731002175853884774869567645561244584131361410908161
  agreementNumerator := 512754
  multiplicity := 13
  bandLower := 5
  taylorCutoff := 24
  exceptionalCount := 8210316778177167673
  listSize := 5089296970
  queries := 115
  initialOodSamples := 2
  powThreshold := 18786624067678312
  nominalQueries := 127
  zeroSlackQueryReference := 119
  fieldBytes := 8
  extensionBytes := 24

/-- The BN254 row has rate one quarter, the expected interleaved vector size, and agreement beyond
the finite Johnson comparison used by the source checker. -/
theorem bn254_code_arithmetic :
    bn254.k * 4 = bn254.n ∧
      bn254.interleavingWidth * bn254.k = bn254.vectorSize ∧
      bn254.agreementNumerator ^ 2 < bn254.n * (bn254.k - 1) := by
  norm_num [bn254]

/-- Every changed BN254 error slot is at most `2^-128`, expressed without rational division. -/
theorem bn254_changed_slots_meet_target :
    bn254.listSize * (bn254.listSize - 1) * (bn254.vectorSize - 1) * 2 ^ 128 ≤
        2 * bn254.fieldSize ∧
      bn254.exceptionalCount * 2 ^ 128 ≤ bn254.fieldSize ∧
      2 * bn254.listSize * 2 ^ 128 ≤ bn254.fieldSize ∧
      (bn254.exceptionalCount + 2 * bn254.listSize) * 2 ^ 128 ≤ bn254.fieldSize ∧
      2 * (1 + bn254.queries) * 160 * 2 ^ 128 ≤ bn254.fieldSize := by
  norm_num [bn254]

/-- The BN254 query contribution meets `2^-128` at 109 queries and exceeds it at 108. -/
theorem bn254_query_selection :
    (bn254.powThreshold + 1) * bn254.agreementNumerator ^ bn254.queries * 2 ^ 128 ≤
        2 ^ 64 * bn254.n ^ bn254.queries ∧
      2 ^ 64 * bn254.n ^ (bn254.queries - 1) <
        (bn254.powThreshold + 1) *
          bn254.agreementNumerator ^ (bn254.queries - 1) * 2 ^ 128 := by
  norm_num [bn254]

/-- The checker's conservative BN254 raw-payload lower bounds are 4032 bytes against the nominal
profile and 2240 bytes against its auxiliary zero-slack reference. -/
theorem bn254_payload_lower_bounds :
    (bn254.nominalQueries - bn254.queries) *
          (bn254.interleavingWidth * bn254.fieldBytes - 32) -
        (bn254.initialOodSamples - 1) * bn254.extensionBytes = 4032 ∧
      (bn254.zeroSlackQueryReference - bn254.queries) *
          (bn254.interleavingWidth * bn254.fieldBytes - 32) -
        (bn254.initialOodSamples - 1) * bn254.extensionBytes = 2240 := by
  norm_num [bn254]

/-- The cubic Goldilocks row has rate one quarter, the expected interleaved vector size, and
agreement beyond the finite Johnson comparison used by the source checker. -/
theorem goldilocksCubic_code_arithmetic :
    goldilocksCubic.k * 4 = goldilocksCubic.n ∧
      goldilocksCubic.interleavingWidth * goldilocksCubic.k = goldilocksCubic.vectorSize ∧
      goldilocksCubic.agreementNumerator ^ 2 <
        goldilocksCubic.n * (goldilocksCubic.k - 1) := by
  norm_num [goldilocksCubic]

/-- Every changed cubic Goldilocks error slot is at most `2^-128`, expressed without rational
division. The initial out-of-domain term includes both extension-field samples. -/
theorem goldilocksCubic_changed_slots_meet_target :
    goldilocksCubic.listSize * (goldilocksCubic.listSize - 1) *
          (goldilocksCubic.vectorSize - 1) ^ 2 * 2 ^ 128 ≤
        2 * goldilocksCubic.fieldSize ^ 2 ∧
      goldilocksCubic.exceptionalCount * 2 ^ 128 ≤ goldilocksCubic.fieldSize ∧
      2 * goldilocksCubic.listSize * 2 ^ 128 ≤ goldilocksCubic.fieldSize ∧
      (goldilocksCubic.exceptionalCount + 2 * goldilocksCubic.listSize) * 2 ^ 128 ≤
        goldilocksCubic.fieldSize ∧
      2 * (1 + goldilocksCubic.queries) * 160 * 2 ^ 128 ≤ goldilocksCubic.fieldSize := by
  norm_num [goldilocksCubic]

/-- The cubic Goldilocks query contribution meets `2^-128` at 115 queries and exceeds it at 114. -/
theorem goldilocksCubic_query_selection :
    (goldilocksCubic.powThreshold + 1) *
          goldilocksCubic.agreementNumerator ^ goldilocksCubic.queries * 2 ^ 128 ≤
        2 ^ 64 * goldilocksCubic.n ^ goldilocksCubic.queries ∧
      2 ^ 64 * goldilocksCubic.n ^ (goldilocksCubic.queries - 1) <
        (goldilocksCubic.powThreshold + 1) *
          goldilocksCubic.agreementNumerator ^ (goldilocksCubic.queries - 1) * 2 ^ 128 := by
  norm_num [goldilocksCubic]

/-- The checker's conservative cubic Goldilocks raw-payload lower bounds are 360 bytes against the
nominal profile and 104 bytes against its auxiliary zero-slack reference. -/
theorem goldilocksCubic_payload_lower_bounds :
    (goldilocksCubic.nominalQueries - goldilocksCubic.queries) *
          (goldilocksCubic.interleavingWidth * goldilocksCubic.fieldBytes - 32) -
        (goldilocksCubic.initialOodSamples - 1) * goldilocksCubic.extensionBytes = 360 ∧
      (goldilocksCubic.zeroSlackQueryReference - goldilocksCubic.queries) *
          (goldilocksCubic.interleavingWidth * goldilocksCubic.fieldBytes - 32) -
        (goldilocksCubic.initialOodSamples - 1) * goldilocksCubic.extensionBytes = 104 := by
  norm_num [goldilocksCubic]

end ArkLibExamples.ReedSolomon.ProveKit
