/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.Data.Polynomial.FunctionFieldAlgorithms.CommonCenter.FiniteEquations
public import CompPoly.LinearAlgebra.Dense.Kernel
public import Mathlib.LinearAlgebra.Span.Basic

/-!
# Executable identity search for a finite generated ideal

The columns are all products of a coordinate basis vector with a supplied denominator.
The homogeneous system solves for an identity constrained to their span. CompPoly's kernel
program supplies candidates, which are checked against the original multiplication table.
Thus soundness does not depend on a correctness theorem for its row reducer. Failure is
explicit and distinct from a proved zero span. Completeness of candidate extraction is not
claimed here. Ideal closure requires the usual multiplication-table laws, proved separately.
-/

@[expose] public section

namespace Polynomial.FunctionFieldAlgorithms.CommonCenter.IdealIdentity

open scoped BigOperators

variable {K : Type*} [Field K] {d m : ℕ}

/-- Coordinates in the supplied multiplication table. -/
abbrev Coordinates (K : Type*) (d : ℕ) := Fin d → K

/-- Multiplication by the `s`-th coordinate basis vector. -/
def basisOperator (table : MultiplicationTable K d) (s : Fin d) :
    Module.End K (Coordinates K d) :=
  Matrix.mulVecLin (fun k j => table s j k)

/-- Linear multiplication operator assembled from the table. -/
def leftOperator (table : MultiplicationTable K d) (x : Coordinates K d) :
    Module.End K (Coordinates K d) := ∑ s, x s • basisOperator table s

/-- Bilinear multiplication specified by the input table. No ring laws are assumed. -/
def multiply (table : MultiplicationTable K d) (x y : Coordinates K d) :
    Coordinates K d := leftOperator table x y

/-- All coordinate basis multiples of all denominators, including zero columns. -/
def generator (table : MultiplicationTable K d) (c : Fin m → Coordinates K d)
    (j : Fin (m * d)) : Coordinates K d :=
  let pair := finProdFinEquiv.symm j
  basisOperator table pair.2 (c pair.1)

/-- The computed generated space. Under associative unital table laws, this is the
ideal generated by the supplied denominators. -/
def generatedSpace (table : MultiplicationTable K d) (c : Fin m → Coordinates K d) :
    Submodule K (Coordinates K d) := Submodule.span K (Set.range (generator table c))

/-- Linear combination of the actual generated columns. -/
def assemble (table : MultiplicationTable K d) (c : Fin m → Coordinates K d)
    (weights : Fin (m * d) → K) : Coordinates K d :=
  ∑ j, weights j • generator table c j

/-- Algebra-valued coefficients of the original denominators, in coordinate storage. -/
def coefficients (weights : Fin (m * d) → K) (l : Fin m) : Coordinates K d :=
  fun s => weights (finProdFinEquiv (l, s))

/-- Identity equations on all generators; these are decidable finite coordinate equations. -/
def IdentityEquations (table : MultiplicationTable K d) (c : Fin m → Coordinates K d)
    (weights : Fin (m * d) → K) : Prop :=
  ∀ j, multiply table (assemble table c weights) (generator table c j) = generator table c j

/-- Coefficient matrix of the inhomogeneous identity equations. -/
def identityMatrix (table : MultiplicationTable K d) (c : Fin m → Coordinates K d) :
    Matrix (Fin (m * d) × Fin d) (Fin (m * d)) K :=
  fun row col => multiply table (generator table c col) (generator table c row.1) row.2

/-- Homogenized identity equations: the extra first column is minus the target generator. -/
def denseIdentityMatrix (table : MultiplicationTable K d)
    (c : Fin m → Coordinates K d) : CompPoly.DenseMatrix K :=
  CompPoly.DenseMatrix.ofFn ((m * d) * d) (1 + m * d) fun row col =>
    if hr : row < (m * d) * d then
      let pair : Fin (m * d) × Fin d := finProdFinEquiv.symm ⟨row, hr⟩
      if col = 0 then -(generator table c pair.1 pair.2)
      else if hc : col - 1 < m * d then identityMatrix table c pair ⟨col - 1, hc⟩ else 0
    else 0

/-- Run the supplied row-reduction implementation on the concrete identity equations. -/
def kernelCandidates [BEq K] (table : MultiplicationTable K d)
    (c : Fin m → Coordinates K d) : Array (Array K) :=
  (denseIdentityMatrix table c).homogeneousKernelBasis

/-- Dehomogenize and verify a candidate in the original equations. The check, not
an assumed property of the row reducer, certifies the returned weights. -/
def checkCandidate [DecidableEq K] (table : MultiplicationTable K d)
    (c : Fin m → Coordinates K d) (candidate : Array K) :
    Option {weights : Fin (m * d) → K // IdentityEquations table c weights} :=
  let t := candidate.getD 0 0
  if t = 0 then none
  else
    let weights : Fin (m * d) → K := fun j => candidate.getD (j.val + 1) 0 / t
    if h : ∀ j, multiply table (assemble table c weights) (generator table c j) =
        generator table c j then some ⟨weights, h⟩ else none

/-- A proved empty span, a checked identity, or an explicit arithmetic-search failure. -/
inductive Result (table : MultiplicationTable K d) (c : Fin m → Coordinates K d) where
  /-- Every generated column is zero. This is not arithmetic failure. -/
  | empty (zero_columns : ∀ j, generator table c j = 0)
  /-- Weights obtained by executing elimination and checking the identity equations. -/
  | identity (weights : Fin (m * d) → K) (equations : IdentityEquations table c weights)
  /-- No checked dehomogenizable candidate was found. -/
  | failure

/-- Compute the ideal's identity from its table and denominators, with no supplied ideal,
idempotent, factorization, or success oracle. -/
def run [BEq K] [DecidableEq K] (table : MultiplicationTable K d)
    (c : Fin m → Coordinates K d) : Result table c :=
  if hz : ∀ j, generator table c j = 0 then .empty hz
  else
    match (kernelCandidates table c).toList.findSome? (checkCandidate table c) with
    | some solution => .identity solution.val solution.property
    | none => .failure

/-- A stable observable tag for branch-distinguishing tests and callers. -/
def Result.tag {table : MultiplicationTable K d} {c : Fin m → Coordinates K d} :
    Result table c → Nat
  | .empty _ => 0
  | .identity _ _ => 1
  | .failure => 2

/-- A zero generated space is recognized before any elimination is attempted. -/
theorem run_empty_of_zero_columns [BEq K] [DecidableEq K]
    (table : MultiplicationTable K d) (c : Fin m → Coordinates K d)
    (hz : ∀ j, generator table c j = 0) : (run table c).tag = 0 := by
  simp [run, hz, Result.tag]

/-- The zero-dimensional boundary algebra is always proved empty. -/
theorem run_zero_dimension [BEq K] [DecidableEq K]
    (table : MultiplicationTable K 0) (c : Fin m → Coordinates K 0) :
    (run table c).tag = 0 :=
  run_empty_of_zero_columns table c (fun _ => Subsingleton.elim _ _)

end Polynomial.FunctionFieldAlgorithms.CommonCenter.IdealIdentity
