/-
Copyright (c) 2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tobias Rothmann
-/
module

public import ArkLib.Data.GroupTheory.PrimeOrder
public import Mathlib.Algebra.Field.ZMod

/-!
# Algebraic Support for KZG-Style SRSes

This file contains the shared powers-of-τ SRS API and reusable prime-order group lemmas used by
KZG, t-SDH, and ARSDH reductions.

## Notation

* `Groups.PowerSrs.tower` is a vector of powers of one group element.
* `Groups.PowerSrs.generate` builds the prover and verifier SRS vectors.

## References

This file contains general algebraic support lemmas and does not cite an external paper directly.
-/

@[expose] public section

namespace Groups

section PrimeOrder

variable {G : Type} [Group G] {p : outParam ℕ} [Fact (Nat.Prime p)]
  [PrimeOrderWith G p]

namespace PowerSrs

variable {G₁ : Type} [Group G₁] [PrimeOrderWith G₁ p] {g₁ : G₁}
  {G₂ : Type} [Group G₂] [PrimeOrderWith G₂ p] {g₂ : G₂}

/-- The vector of length `n + 1` consisting of the monomial powers
`#v[g, g ^ τ, g ^ (τ ^ 2), ..., g ^ (τ ^ n)]`. -/
def tower (g : G) (τ : ZMod p) (n : ℕ) : Vector G (n + 1) :=
  .ofFn (fun i => g ^ (τ.val ^ i.val))

/-- The monomial powers-of-τ SRS used by KZG, t-SDH, and ARSDH:
`(g₁, g₁^τ, ..., g₁^(τ^n)), (g₂, g₂^τ)`. -/
def generate (n : ℕ) (τ : ZMod p) : Vector G₁ (n + 1) × Vector G₂ 2 :=
  (tower g₁ τ n, tower g₂ τ 1)

omit [PrimeOrderWith G₂ p] in
/-- If the first prover SRS element generated by `generate` is nontrivial, then its base
generator is nontrivial. -/
lemma generator_ne_one_of_generate
    {n : ℕ} {τ : ZMod p} {srs : Vector G₁ (n + 1) × Vector G₂ 2}
    (hsrs : srs = generate (g₁ := g₁) (g₂ := g₂) n τ) (hgen : srs.1[0] ≠ 1) :
    g₁ ≠ 1 := by
  rw [hsrs] at hgen
  simpa [generate, tower] using hgen

end PowerSrs

/-- A nontrivial element of a prime-order group has order `p`. -/
lemma orderOf_eq_prime_of_ne_one (x : G) (hx : x ≠ 1) : orderOf x = p := by
  have hdvd := orderOf_dvd_natCard (G := G) x
  rw [PrimeOrderWith.hCard] at hdvd
  rcases (Nat.dvd_prime Fact.out).1 hdvd with h1 | hp'
  · exact absurd (orderOf_eq_one_iff.1 h1) hx
  · exact hp'

/-- If `g ^ a = 1` in a prime-order group generated by a nontrivial element of order `p`,
then the `ZMod p` exponent is zero. -/
lemma zmod_eq_zero_of_gpow_eq_one {g : G} (hord : orderOf g = p) {a : ZMod p}
    (ha : g ^ a.val = 1) : a = 0 := by
  have hdvd := orderOf_dvd_of_pow_eq_one ha
  rw [hord] at hdvd
  apply ZMod.val_injective p
  have hval : a.val = 0 := by
    by_contra h
    exact absurd (ZMod.val_lt a) (not_lt.mpr (Nat.le_of_dvd (Nat.pos_of_ne_zero h) hdvd))
  simpa using hval

omit [PrimeOrderWith G p] in
/-- If two natural exponents are equal when cast to `ZMod p`, then powers by them agree for an
element of order `p`. -/
lemma gpow_eq_of_nat_cast_eq {g : G} (hord : orderOf g = p) (a b : ℕ)
    (hab : ((a : ℕ) : ZMod p) = ((b : ℕ) : ZMod p)) : g ^ a = g ^ b := by
  conv_lhs => rw [← pow_mod_orderOf, hord]
  conv_rhs => rw [← pow_mod_orderOf, hord]
  congr 1
  have := congr_arg ZMod.val hab
  rwa [ZMod.val_natCast, ZMod.val_natCast] at this

omit [PrimeOrderWith G p] in
/-- Group division of powers equals the power of the `ZMod p` difference. -/
lemma gpow_div_eq {g : G} (hord : orderOf g = p) (a b : ZMod p) :
    g ^ a.val / g ^ b.val = g ^ (a - b).val := by
  rw [div_eq_iff_eq_mul, ← pow_add]
  exact gpow_eq_of_nat_cast_eq hord _ _ (by push_cast [ZMod.natCast_zmod_val]; ring)

omit [PrimeOrderWith G p] in
/-- Product of `.val`s as exponent equals `ZMod p` product's `.val` as exponent. -/
lemma gpow_val_mul_eq {g : G} (hord : orderOf g = p) (a b : ZMod p) :
    g ^ (a.val * b.val) = g ^ (a * b).val :=
  gpow_eq_of_nat_cast_eq hord _ _ (by push_cast [ZMod.natCast_zmod_val]; ring)

/-- Every element of a prime-order group is a `ZMod p` power of a nontrivial generator. -/
lemma exists_zmod_power_of_generator {g : G} (hpG : Nat.card G = p) (hg : g ≠ 1)
    (hord : orderOf g = p) (x : G) : ∃ a : ZMod p, x = g ^ a.val := by
  obtain ⟨k, hk⟩ : ∃ k : ℕ, g ^ k = x := mem_powers_of_prime_card hpG hg
  exact ⟨(k : ZMod p), by rw [ZMod.val_natCast, ← hk, ← pow_mod_orderOf g k, hord]⟩

end PrimeOrder

end Groups
