/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import ArkLib.Data.CodingTheory.ReedSolomon.HiddenDerivative.RootFinding.Taylor.Cuts
import ArkLib.ToMathlib.AlgebraicGeometry.PrincipalOpen.Finite


/-! # Agreement-cut geometry on the regular rational Taylor chart -/

open PolynomialDifferential


noncomputable section

open MvPolynomial
open AffineHilbert

namespace ReedSolomon.HiddenDerivative

variable {F : Type*} [Field F] {r : ℕ}

/-- The ideal generated by the common Taylor numerators whose coefficient indices
are at least the target message degree. -/
def highTaylorCutsIdeal (center : F) (Q : DifferentialPolynomial F r) (K k : ℕ) :
    Ideal (MvPolynomial (Fin (r + 1)) F) :=
  Ideal.span (Set.range fun l : {l : Fin K // k ≤ l.val} ↦
    commonTaylorNumerator center Q K l.val)

/-- The regular points of `V(P)` satisfying a fixed family of agreement cuts. -/
def regularAgreementCutLocus (P : Ideal (MvPolynomial (Fin (r + 1)) F))
    (center : F) (Q : DifferentialPolynomial F r) (K : ℕ)
    {ι : Type*} (domain : ι → F) (received : ι → F) : Set (Fin (r + 1) → F) :=
  {jet | jet ∈ principalOpenZeroLocus P (initialJetSeparant center Q) ∧
    ∀ i, aeval jet (taylorAgreementEquation center Q K (domain i) (received i)) = 0}

/-- Once the high Taylor cuts hold, agreement at `k` distinct coordinates leaves
at most one point on the regular chart. -/
theorem regularAgreementCutLocus_subsingleton
    (center : F) (Q : DifferentialPolynomial F r) (K k : ℕ) (hK : r < K)
    (P : Ideal (MvPolynomial (Fin (r + 1)) F))
    (hhigh : highTaylorCutsIdeal center Q K k ≤ P)
    (domain : Fin k ↪ F) (received : Fin k → F) :
    (regularAgreementCutLocus P center Q K domain received).Subsingleton := by
  intro jet hjet jet' hjet'
  rcases hjet with ⟨⟨hjetP, hjetS⟩, hjetCuts⟩
  rcases hjet' with ⟨⟨hjetP', hjetS'⟩, hjetCuts'⟩
  apply eq_of_high_cuts_and_agreement_cuts center Q K k hK domain received
    jet jet' hjetS hjetS'
  · intro l hl
    exact hjetP _ (hhigh (Ideal.subset_span ⟨⟨l, hl⟩, rfl⟩))
  · intro l hl
    exact hjetP' _ (hhigh (Ideal.subset_span ⟨⟨l, hl⟩, rfl⟩))
  · exact hjetCuts
  · exact hjetCuts'

/-- Finset-indexed form used by incidence arguments: any chosen `k` received
coordinates cut the regular chart in at most one point. -/
theorem eq_of_mem_principalOpen_of_highCuts_of_agreementFinset
    (center : F) (Q : DifferentialPolynomial F r) (K k : ℕ) (hK : r < K)
    {n : ℕ} (P : Ideal (MvPolynomial (Fin (r + 1)) F))
    (hhigh : highTaylorCutsIdeal center Q K k ≤ P)
    (domain : Fin n ↪ F) (received : Fin n → F)
    (T : Finset (Fin n)) (hT : T.card = k)
    {jet jet' : Fin (r + 1) → F}
    (hjet : jet ∈ principalOpenZeroLocus P (initialJetSeparant center Q))
    (hjet' : jet' ∈ principalOpenZeroLocus P (initialJetSeparant center Q))
    (hcuts : ∀ i ∈ T,
      aeval jet (taylorAgreementEquation center Q K (domain i) (received i)) = 0)
    (hcuts' : ∀ i ∈ T,
      aeval jet' (taylorAgreementEquation center Q K (domain i) (received i)) = 0) :
    jet = jet' := by
  classical
  let e : Fin k ≃ T := (finCongr (by simpa using hT.symm)).trans
    (Fintype.equivFin T).symm
  let domainT : Fin k ↪ F := e.toEmbedding.trans
    ((Function.Embedding.subtype _).trans domain)
  let receivedT : Fin k → F := fun i ↦ received (e i).val
  apply regularAgreementCutLocus_subsingleton center Q K k hK P hhigh domainT receivedT
  · exact ⟨hjet, fun i ↦ hcuts (e i).val (e i).property⟩
  · exact ⟨hjet', fun i ↦ hcuts' (e i).val (e i).property⟩

end ReedSolomon.HiddenDerivative
