/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import ArkLib.Data.CodingTheory.ReedSolomon.ListDecoding.ExactOutput
public import ArkLib.Data.CodingTheory.ReedSolomon.Agreement
public import ArkLib.Data.CodingTheory.ReedSolomon.ListDecoding.Output.CandidateFilterSemantics
public import ArkLib.Data.Polynomial.CoefficientList
public import ArkLib.ToCompPoly.Univariate.Lagrange

-- The executable coefficient bridge intentionally reduces the canonical and raw arrays.
import all CompPoly.Univariate.Basic
import all CompPoly.Univariate.Raw.Core
/-!
# Interpolation and checking for a sample of received positions

This file contains the reusable, executable operation that interpolates a polynomial through a
sample of received positions, materializes its fixed-width coefficient vector, and checks its
degree and full received-word agreement. It is independent of how a decoder obtains its samples.
-/

@[expose] public section

namespace ReedSolomon.ListDecoding.SampleInterpolation

open Polynomial JetHornerMachine
open CompPoly.CPolynomial

variable {F : Type*} [Field F] [DecidableEq F] [BEq F] [LawfulBEq F] {n : ℕ}

/-- The computable interpolation polynomial attached to a sample of received positions. -/
def interpolation (domain : Fin n ↪ F) (received : Fin n → F) (sample : Finset (Fin n)) :
    CompPoly.CPolynomial F :=
  CompPoly.CPolynomial.CLagrange.interpolate sample domain received

/-- Convert an ascending computable polynomial to the canonical descending vector of width `k`.
When the input fits, including width zero, the result has exactly that width. -/
def coefficientVector (k : ℕ) (p : CompPoly.CPolynomial F) : List F :=
  Polynomial.CoefficientList.padReverse k p.val.toList

omit [DecidableEq F] in
private theorem interpolation_size_le (domain : Fin n ↪ F) (received : Fin n → F)
    (sample : Finset (Fin n)) {k : ℕ} (hcard : sample.card = k) :
    (interpolation domain received sample).val.size ≤ k := by
  let p := interpolation domain received sample
  have hdegreePoly : p.toPoly.degree < k := by
    dsimp [p, interpolation]
    rw [CompPoly.CPolynomial.CLagrange.cinterpolate_eq_interpolate]
    simpa [hcard] using
      (Lagrange.degree_interpolate_lt (s := sample) (v := domain) (r := received)
        domain.injective.injOn)
  have hdegree : p.degree < k := by
    rwa [CompPoly.CPolynomial.degree_toPoly]
  change p.val.size ≤ k
  cases hsize : p.val.size with
  | zero => simp
  | succ m =>
      simp only [CompPoly.CPolynomial.degree, hsize] at hdegree
      exact Nat.succ_le_iff.mpr (by exact_mod_cast hdegree)

omit [DecidableEq F] [BEq F] [LawfulBEq F] in
private theorem coefficientVector_length (k : ℕ) (p : CompPoly.CPolynomial F)
    (hsize : p.val.size ≤ k) : (coefficientVector k p).length = k := by
  exact Polynomial.CoefficientList.padReverse_length k p.val.toList (by simpa using hsize)

omit [DecidableEq F] in
private theorem ascendingPolynomial_toList (p : CompPoly.CPolynomial F) :
    Polynomial.CoefficientList.ascendingPolynomial p.val.toList = p.toPoly := by
  ext j
  rw [Polynomial.CoefficientList.ascendingPolynomial_coeff,
    ← CompPoly.CPolynomial.coeff_toPoly]
  simp [CompPoly.CPolynomial.coeff, CompPoly.CPolynomial.Raw.coeff]

omit [DecidableEq F] in
private theorem coefficientVector_polynomial (k : ℕ) (p : CompPoly.CPolynomial F) :
    coefficientPolynomial (coefficientVector k p) = p.toPoly := by
  rw [coefficientVector, Polynomial.CoefficientList.padReverse_polynomial,
    ascendingPolynomial_toList]

/-- Candidate generated by interpolating one position sample. -/
def sampleCandidate (domain : Fin n ↪ F) (received : Fin n → F) (k : ℕ)
    (sample : Finset (Fin n)) : List F :=
  coefficientVector k (interpolation domain received sample)

omit [DecidableEq F] in
/-- A sample of cardinality `k` produces exactly the repository's physical output width. -/
theorem sampleCandidate_length (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) :
    (sampleCandidate domain received k sample).length = k := by
  exact coefficientVector_length k _ (interpolation_size_le domain received sample hcard)

omit [DecidableEq F] in
/-- The materialized vector represents the mathematical Lagrange interpolant of the sample. -/
theorem sampleCandidate_polynomial (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) :
    coefficientPolynomial (sampleCandidate domain received k sample) =
      Lagrange.interpolate sample domain received := by
  rw [sampleCandidate, coefficientVector_polynomial]
  exact CompPoly.CPolynomial.CLagrange.cinterpolate_eq_interpolate

/-- Execute interpolation and the existing degree/agreement filter for one sample. -/
def checkedCandidate (domain : Fin n ↪ F) (received : Fin n → F) (k A : ℕ)
    (sample : Finset (Fin n)) : Option (List F) :=
  CandidateFilterMachine.result k k A (sampleCandidate domain received k sample)
    (List.ofFn fun i ↦ (domain i, received i))

/-- A successful sample check returns a fixed-width vector for the sample interpolant that passes
the degree and full received-word agreement tests. -/
theorem checkedCandidate_properties (domain : Fin n ↪ F) (received : Fin n → F)
    (k A : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) (cs : List F)
    (hchecked : checkedCandidate domain received k A sample = some cs) :
    cs.length = k ∧
      coefficientPolynomial cs = Lagrange.interpolate sample domain received ∧
      (coefficientPolynomial cs).degree < k ∧
      A ≤ Code.agree (evalOnPoints domain (coefficientPolynomial cs)) received := by
  have hsource := sampleCandidate_length domain received k sample hcard
  have hrepresented := CandidateFilterMachine.result_represents hsource le_rfl hchecked
  have hchecked' : CandidateFilterMachine.result k k A
      (sampleCandidate domain received k sample)
      (List.ofFn fun i ↦ (domain i, received i)) = some cs := hchecked
  have haccepted := (CandidateFilterMachine.result_ne_none_iff k k A
    (sampleCandidate domain received k sample) hsource le_rfl domain received).mp (by
      rw [hchecked']
      simp)
  exact ⟨hrepresented.1,
    hrepresented.2.trans (sampleCandidate_polynomial domain received k sample),
    hrepresented.2 ▸ haccepted.1, hrepresented.2 ▸ haccepted.2⟩

/-- If a sample candidate meets the full received-word agreement threshold, checking that sample
returns the candidate itself. -/
theorem checkedCandidate_of_agreement (domain : Fin n ↪ F)
    (received : Fin n → F) (k A : ℕ) (sample : Finset (Fin n))
    (hcard : sample.card = k)
    (hagreement : A ≤ Code.agree
      (evalOnPoints domain (coefficientPolynomial (sampleCandidate domain received k sample)))
      received) :
    checkedCandidate domain received k A sample =
      some (sampleCandidate domain received k sample) := by
  have hlength := sampleCandidate_length domain received k sample hcard
  have hdegree :
      (coefficientPolynomial (sampleCandidate domain received k sample)).degree < k := by
    simpa only [hlength] using
      degree_coefficientPolynomial_lt_length (sampleCandidate domain received k sample)
  have hsome := (CandidateFilterMachine.result_ne_none_iff k k A
    (sampleCandidate domain received k sample) hlength le_rfl domain received).mpr
      ⟨hdegree, hagreement⟩
  cases hresult : checkedCandidate domain received k A sample with
  | none => exact (hsome (by simpa [checkedCandidate] using hresult)).elim
  | some out =>
      have hrepresented := CandidateFilterMachine.result_represents hlength le_rfl hresult
      have hout : out = sampleCandidate domain received k sample :=
        coefficientVectors_eq (hrepresented.1.trans hlength.symm) hrepresented.2
      exact congrArg some hout

omit [BEq F] [LawfulBEq F] in
/-- A polynomial of degree below the sample cardinality equals the sample interpolant whenever it
agrees with the received word at every sampled position. -/
theorem interpolate_eq_of_agrees_on (domain : Fin n ↪ F) (received : Fin n → F)
    (k : ℕ) (sample : Finset (Fin n)) (hcard : sample.card = k) (P : F[X])
    (hdegree : P.degree < k) (hagreement : sample ⊆ polynomialAgreementSet domain received P) :
    Lagrange.interpolate sample domain received = P := by
  apply Polynomial.eq_of_degrees_lt_of_eval_index_eq sample domain.injective.injOn
  · simpa [hcard] using
      Lagrange.degree_interpolate_lt (s := sample) (v := domain) (r := received)
        domain.injective.injOn
  · simpa [hcard] using hdegree
  · intro i hi
    rw [Lagrange.eval_interpolate_at_node received domain.injective.injOn hi]
    exact (Finset.mem_filter.mp (hagreement hi)).2.symm

end ReedSolomon.ListDecoding.SampleInterpolation
