/-
Copyright (c) 2024-2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao, Katerina Hristova, František Silváši, Julian Sutherland,
         Ilia Vlasov, Chung Thai Nguyen
-/
module

public import ArkLib.Data.CodingTheory.ProximityGap.BCIKS20.ErrorBound

/-! # Weighted correlated agreement over curves and affine spaces

Weighted-agreement forms of correlated agreement for Reed–Solomon codes: a random point of a
low-degree curve or of an affine subspace with high `μ`-weighted agreement forces joint weighted
agreement of the generating words. The agreement parameter `α` corresponds to the distance
parameter via `δ = 1 - α`.

## References

- [BCIKS20] Ben-Sasson, Carmon, Ishai, Kopparty, Saraf, *Proximity Gaps for Reed–Solomon Codes*
  (ePrint 2020/654): Theorems 7.1, 7.3, and 7.4.
-/

@[expose] public section

namespace ProximityGap

namespace WeightedAgreement

open NNReal Finset Function ProbabilityTheory ReedSolomon Uniform
open scoped BigOperators Pointwise ProbabilityTheory

section ProbabilityTheorems

variable {ι : Type} [Fintype ι] [Nonempty ι]
variable {F : Type} [Field F] [Fintype F] [DecidableEq F]

instance {domain : ι ↪ F} {deg : ℕ} : Nonempty (finCarrier domain deg) := by
  rcases Submodule.nonempty (ReedSolomon.code domain deg) with ⟨v, hv⟩
  refine ⟨v, ?_⟩
  simpa [ReedSolomon.finCarrier, Set.mem_toFinset] using hv

/-- Theorem 7.1 (Weighted correlated agreement over curves — Version I) of [BCIKS20].

Take a Reed-Solomon code of length `ι` and degree `deg`, an agreement parameter `α ∈ (√ρ, 1)`,
and a curve generated by vectors `u`, such that the probability that a random point on the curve
has `μ`-weighted agreement at least `α` with the code exceeds `l · ε`.
Then, the words `u` have weighted correlated agreement.

The paper takes `ε` to be the error of Theorem 1.2 *at* `η = min (α - √ρ) (√ρ / 20)`. The Johnson
branch of `errorBound` is stated in terms of the distance parameter, as `min (1 - √ρ - δ) (√ρ/20)`;
the two agree exactly at `δ = 1 - α`, which is why `ε` is `errorBound (1 - α)` here. Evaluating
`errorBound` at a free, otherwise-unconstrained `δ` would let the caller push `δ ≥ 1 - √ρ`, where
`errorBound` returns `0` and the proximity hypothesis degenerates. -/
theorem weighted_correlated_agreement_for_parameterized_curves [DecidableEq ι]
    {l : ℕ} {k : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M : ℕ}
    {α : ℝ≥0}
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) :
    letI sqrtRate := ReedSolomon.sqrtRate deg domain
    (hα : sqrtRate < α) →
    (hα₁ : α < 1) →
    letI ε := ProximityGap.errorBound (1 - α) deg domain
    letI pr :=
      let curvePts := Curve.polynomialCurveFinite (F := F) (A := F) u
      Pr_{let y ←$ᵖ curvePts}[agree_set μ y (finCarrier domain deg) ≥ α]
    (hproximity : pr > (l + 1 : NNReal) * ε) →
    (h_additionally : pr ≥
      ENNReal.ofReal (
        ((l + 1) * (M * Fintype.card ι + 1) : ℝ) / (Fintype.card F : ℝ)
        *
        (1 / min (α - sqrtRate) (sqrtRate / 20) + 3 / sqrtRate)
      )
    ) →
    ∃ ι' : Finset ι, ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ ι' ≥ α ∧
      ∀ i, ∀ x ∈ ι', u i x = v i x := by
  sorry

/-- Weighted correlated agreement over curves.
Take a Reed-Solomon code of length `ι` and degree `deg`, a proximity-error parameter
pair `(δ, ε)` and a curve generated by vectors `u`, such that the probability that a random
point on the curve is `δ`-close to Reed-Solomon code is at most `ε`.
Then, the words `u` have weighted correlated agreement.

Version with different bounds. -/
theorem weighted_correlated_agreement_for_parameterized_curves'
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F} {δ : ℝ≥0}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M m : ℕ}
    (hm : 3 ≤ m)
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ))
    {α : ℝ≥0} :
    letI sqrtRate := ReedSolomon.sqrtRate deg domain
    letI S : Finset F := {
      z : F |
        agree_set μ (Curve.polynomialCurveEval (F := F) (A := F) u z) (finCarrier domain deg) ≥ α
    }
    (hα : sqrtRate * (1 + 1 / (2 * m : ℝ)) ≤ α) →
    (hS :
      Finset.card S >
        max ((1 + 1 / (2 * m : ℝ)) ^ 7 * m ^ 7 * (Fintype.card ι) ^ 2 * (l + 1) /
            (3 * sqrtRate ^ 3))
          ((2 * m + 1) * (M * Fintype.card ι + 1) * (l + 1) / sqrtRate.toReal)
    ) →
    ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ { i : ι | ∀ j, u j i = v j i } ≥ α := by
  sorry

/-- Theorem 7.3 (Weighted correlated agreement over affine spaces) of [BCIKS20].

Take a Reed-Solomon code of length `ι` and degree `deg`, an agreement parameter `α ∈ (√ρ, 1)`,
and the affine space `U = u₀ + span{u₁, …, u_l}` generated by `u`, such that the probability that
a random point of `U` has `μ`-weighted agreement at least `α` with the code exceeds `ε`.
Then, the words `u` have weighted correlated agreement.

Two conventions matter here, and both are load-bearing.

* `ε` is `errorBound (1 - α)`, not `errorBound α`: the paper's `η = min (α - √ρ) (√ρ/20)` matches
  the Johnson branch's `min (1 - √ρ - δ) (√ρ/20)` exactly at `δ = 1 - α`. See
  `weighted_correlated_agreement_for_parameterized_curves`.
* The point set is `Affine.affineSubspaceAtOrigin (u 0) (Fin.tail u)`, whose direction is the
  **linear** span `Submodule.span F {u₁, …, u_l}`. This is not the affine hull of the tail points:
  `affineSpan` of `{u₁}` is the single point `u₁`, so `u₀ +ᵥ affineSpan {u₁}` would collapse the
  whole space to `{u₀ + u₁}` at `l = 0` instead of the line `{u₀ + z u₁ : z ∈ F}`. -/
theorem weighted_correlated_agreement_over_affine_spaces [DecidableEq ι]
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {M : ℕ}
    {α : ℝ≥0} :
    letI sqrtRate := ReedSolomon.sqrtRate deg domain
    (hα : sqrtRate < α) →
    (hα₁ : α < 1) →
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) →
    letI ε := ProximityGap.errorBound (1 - α) deg domain
    letI pr :=
      Pr_{let y ←$ᵖ ↥(Affine.affineSubspaceAtOrigin (F := F) (u 0) (Fin.tail u))}[
        agree_set μ y.1 (finCarrier domain deg) ≥ α]
    pr > ε →
    pr ≥ ENNReal.ofReal (
      ((M * Fintype.card ι + 1) : ℝ) / (Fintype.card F : ℝ)
      *
      (1 / min (α - sqrtRate) (sqrtRate / 20) + 3 / sqrtRate)
    ) →
    ∃ ι' : Finset ι, ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ ι' ≥ α ∧
      ∀ i, ∀ x ∈ ι', u i x = v i x := by
  sorry

/-- Theorem 7.4 (Weighted correlated agreement over affine spaces — Version II) of [BCIKS20].

As `weighted_correlated_agreement_over_affine_spaces`, but in the Johnson regime `α ≥ α₀(ρ, m)`
and with the two-branch bound (7.2) in place of the `η`-form error.

The point set is `Affine.affineSubspaceAtOrigin (u 0) (Fin.tail u)`, whose direction is the
**linear** span `Submodule.span F {u₁, …, u_l}` — not the affine hull of the tail points. -/
theorem weighted_correlated_agreement_over_affine_spaces' [DecidableEq ι]
    {k l : ℕ} {u : Fin (l + 2) → ι → F}
    {deg : ℕ} {domain : ι ↪ F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {M m : ℕ}
    (hm : 3 ≤ m)
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ)) :
    letI sqrtRate := ReedSolomon.sqrtRate deg domain
    letI pr :=
      Pr_{let y ←$ᵖ ↥(Affine.affineSubspaceAtOrigin (F := F) (u 0) (Fin.tail u))}[
        agree_set μ y.1 (finCarrier domain deg) ≥ α]
    (hα : sqrtRate * (1 + 1 / (2 * m : ℝ)) ≤ α) →
    letI numeratorl : ℝ := (1 + 1 / (2 * m : ℝ)) ^ 7 * m ^ 7 * (Fintype.card ι) ^ 2
    letI denominatorl : ℝ := (3 * sqrtRate ^ 3) * Fintype.card F
    letI numeratorr : ℝ := (2 * m + 1) * (M * Fintype.card ι + 1)
    letI denominatorr : ℝ := sqrtRate * Fintype.card F
    pr > ENNReal.ofReal (max (numeratorl / denominatorl) (numeratorr / denominatorr)) →
    ∃ v : Fin (l + 2) → ι → F,
      (∀ i, v i ∈ ReedSolomon.code domain deg) ∧
      mu_set μ { i : ι | ∀ j, u j i = v j i } ≥ α := by
  sorry

end ProbabilityTheorems

section ListAgreementLemmas

variable {ι : Type} [Fintype ι] [Nonempty ι]
variable {F : Type} [Field F] [DecidableEq F]
/-- Lemma 7.5 in [BCIKS20].
This is the "list agreement on a curve implies correlated agreement" lemma.

We are given two lists of functions `u, v : Fin (l + 2) → ι → F`. From these lists we
form the bivariate curve evaluations. Code membership is not needed for this
combinatorial root-counting bound; callers may separately know that every `v i` is a
Reed-Solomon codeword.

* `w x z = Curve.polynomialCurveEval u z x`,
* `wtilde x z = Curve.polynomialCurveEval v z x`.

Fix a finite set `S' ⊆ F` with `S'.card > l + 1`, and a (product) measure `μ` on the
evaluation domain `ι`. Assume that for every `z ∈ S'` the one-dimensional functions
`w · z` and `wtilde · z` have agreement at least `α` with respect to `μ`. Then the set
of points `x` on which all coordinates agree, i.e. `u i x = v i x` for every `i`,
has μ-measure strictly larger than

`α - (l + 1) / (S'.card - (l + 1))`. -/
lemma list_agreement_on_curve_implies_correlated_agreement_bound
    {l : ℕ} {u : Fin (l + 2) → ι → F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {v : Fin (l + 2) → ι → F}
    {S' : Finset F}
    (hS'_card : S'.card > l + 1) :
    letI w (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) u z x
    letI wtilde (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) v z x
    (hS'_agree : ∀ z ∈ S', agree μ (w · z) (wtilde · z) ≥ α) →
    mu_set μ { x : ι | ∀ i, u i x = v i x } >
      α - ((l + 1) : ℝ) / (S'.card - (l + 1)) := by
  dsimp only
  classical
  intro hS'_agree
  let common : Finset ι := {x | ∀ i, u i x = v i x}
  let agreementPoints (x : ι) : Finset F := S'.filter fun z =>
    Curve.polynomialCurveEval u z x = Curve.polynomialCurveEval v z x
  let difference (x : ι) : Polynomial F :=
    ∑ i : Fin (l + 2), Polynomial.monomial i (u i x - v i x)
  have difference_eval (x : ι) (z : F) :
      (difference x).eval z =
        Curve.polynomialCurveEval u z x - Curve.polynomialCurveEval v z x := by
    simp only [difference, Polynomial.eval_finsetSum, Polynomial.eval_monomial,
      Curve.polynomialCurveEval, Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro i _
    ring
  have difference_degree (x : ι) : (difference x).natDegree ≤ l + 1 := by
    apply Polynomial.natDegree_sum_le_of_forall_le
    intro i _
    exact (Polynomial.natDegree_monomial_le _).trans (by omega)
  have difference_ne_zero {x : ι} (hx : x ∉ common) : difference x ≠ 0 := by
    intro hzero
    apply hx
    simp only [common, Finset.mem_filter, Finset.mem_univ, true_and]
    intro i
    have hcoeff := congrArg (fun p : Polynomial F => p.coeff i) hzero
    simp only [difference, Polynomial.finsetSum_coeff, Polynomial.coeff_monomial,
      Polynomial.coeff_zero] at hcoeff
    have : u i x - v i x = 0 := by
      rw [Finset.sum_eq_single i] at hcoeff
      · simpa using hcoeff
      · intro j _ hji
        simp only [if_neg (fun hval => hji (Fin.ext hval))]
      · simp
    exact sub_eq_zero.mp this
  have agreementPoints_card {x : ι} (hx : x ∉ common) :
      (agreementPoints x).card ≤ l + 1 := by
    calc
      (agreementPoints x).card ≤ (difference x).natDegree := by
        apply Polynomial.card_le_degree_of_subset_roots
        intro z hz
        rw [Polynomial.mem_roots (difference_ne_zero hx), Polynomial.IsRoot.def,
          difference_eval]
        exact sub_eq_zero.mpr (Finset.mem_filter.mp hz).2
      _ ≤ l + 1 := difference_degree x
  have agreementPoints_eq {x : ι} (hx : x ∈ common) : agreementPoints x = S' := by
    apply Finset.filter_eq_self.2
    intro z _
    have hx' : ∀ i, u i x = v i x := by simpa [common] using hx
    simp only [Curve.polynomialCurveEval, Finset.sum_apply]
    apply Finset.sum_congr rfl
    intro i _
    simp only [Pi.smul_apply, hx' i]
  have weight_nonneg (x : ι) : 0 ≤ (μ x).1 := (μ x).property.1
  have weight_le_one (x : ι) : (μ x).1 ≤ 1 := (μ x).property.2
  have hsum_lower :
      (S'.card : ℝ) * (α : ℝ) ≤
        ∑ z ∈ S', agree μ
          (fun x => Curve.polynomialCurveEval u z x)
          (fun x => Curve.polynomialCurveEval v z x) := by
    calc
      (S'.card : ℝ) * (α : ℝ) = ∑ _z ∈ S', (α : ℝ) := by simp
      _ ≤ ∑ z ∈ S', agree μ
          (fun x => Curve.polynomialCurveEval u z x)
          (fun x => Curve.polynomialCurveEval v z x) :=
        Finset.sum_le_sum fun z hz => hS'_agree z hz
  have hsum_eq :
      ∑ z ∈ S', agree μ
          (fun x => Curve.polynomialCurveEval u z x)
          (fun x => Curve.polynomialCurveEval v z x) =
        1 / (Fintype.card ι : ℝ) *
          ∑ x : ι, (agreementPoints x).card * (μ x).1 := by
    simp only [agree]
    rw [← Finset.mul_sum]
    congr 1
    push_cast
    simp_rw [Finset.sum_filter]
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro x _
    rw [← Finset.sum_filter]
    simp [agreementPoints, nsmul_eq_mul, mul_comm]
  have hweighted_upper :
      (∑ x : ι, ((agreementPoints x).card : ℚ) * (μ x).1) ≤
        (S'.card : ℚ) * (∑ x ∈ common, (μ x).1) +
          (l + 1 : ℚ) * Fintype.card ι := by
    calc
      (∑ x : ι, ((agreementPoints x).card : ℚ) * (μ x).1) =
          (∑ x ∈ common, ((agreementPoints x).card : ℚ) * (μ x).1) +
            ∑ x ∈ Finset.univ.filter (fun x => x ∉ common),
              ((agreementPoints x).card : ℚ) * (μ x).1 := by
        simpa only [Finset.filter_mem_eq_inter, Finset.univ_inter] using
          (Finset.sum_filter_add_sum_filter_not
            (s := Finset.univ) (p := fun x => x ∈ common)
            (f := fun x => ((agreementPoints x).card : ℚ) * (μ x).1)).symm
      _ ≤ (S'.card : ℚ) * (∑ x ∈ common, (μ x).1) +
            (l + 1 : ℚ) *
              (∑ x ∈ Finset.univ.filter (fun x => x ∉ common), (μ x).1) := by
        apply add_le_add
        · rw [Finset.mul_sum]
          apply Finset.sum_le_sum
          intro x hx
          rw [agreementPoints_eq hx]
        · rw [Finset.mul_sum]
          apply Finset.sum_le_sum
          intro x hx
          exact mul_le_mul_of_nonneg_right
            (by exact_mod_cast agreementPoints_card (Finset.mem_filter.mp hx).2)
            (weight_nonneg x)
      _ ≤ (S'.card : ℚ) * (∑ x ∈ common, (μ x).1) +
            (l + 1 : ℚ) * Fintype.card ι := by
        apply add_le_add_right
        apply mul_le_mul_of_nonneg_left _ (by positivity)
        calc
          (∑ x ∈ Finset.univ.filter (fun x => x ∉ common), (μ x).1) ≤
              ∑ _x ∈ Finset.univ.filter (fun x => x ∉ common), (1 : ℚ) := by
            apply Finset.sum_le_sum
            intro i _
            exact weight_le_one i
          _ ≤ ∑ _x : ι, (1 : ℚ) := by
            exact Finset.sum_le_sum_of_subset_of_nonneg
              (Finset.filter_subset _ _) (fun _ _ _ => by positivity)
          _ = Fintype.card ι := by simp
  have hweighted_upper_real :
      ((∑ x : ι, ((agreementPoints x).card : ℚ) * (μ x).1 : ℚ) : ℝ) ≤
        (S'.card : ℝ) * ((∑ x ∈ common, (μ x).1 : ℚ) : ℝ) +
          (l + 1 : ℝ) * Fintype.card ι := by
    exact_mod_cast hweighted_upper
  have hn_pos : (0 : ℝ) < Fintype.card ι := by positivity
  have hcore :
      (S'.card : ℝ) * (α : ℝ) ≤
        (S'.card : ℝ) * mu_set μ common + (l + 1 : ℝ) := by
    calc
      (S'.card : ℝ) * (α : ℝ) ≤
          ∑ z ∈ S', agree μ
            (fun x => Curve.polynomialCurveEval u z x)
            (fun x => Curve.polynomialCurveEval v z x) := hsum_lower
      _ = 1 / (Fintype.card ι : ℝ) *
          ((∑ x : ι, ((agreementPoints x).card : ℚ) * (μ x).1 : ℚ) : ℝ) := hsum_eq
      _ ≤ 1 / (Fintype.card ι : ℝ) *
          ((S'.card : ℝ) * ((∑ x ∈ common, (μ x).1 : ℚ) : ℝ) +
            (l + 1 : ℝ) * Fintype.card ι) :=
        mul_le_mul_of_nonneg_left hweighted_upper_real (by positivity)
      _ = (S'.card : ℝ) * mu_set μ common + (l + 1 : ℝ) := by
        simp only [mu_set]
        field_simp
  change mu_set μ common >
    (α : ℝ) - (l + 1 : ℝ) / ((S'.card : ℝ) - (l + 1 : ℝ))
  have hcard_real : (l + 1 : ℝ) < S'.card := by exact_mod_cast hS'_card
  have hgap_pos : (0 : ℝ) < (S'.card : ℝ) - (l + 1 : ℝ) := by
    linarith
  have hcard_pos : (0 : ℝ) < S'.card := by
    linarith
  have hfraction :
      (l + 1 : ℝ) / S'.card <
        (l + 1 : ℝ) / ((S'.card : ℝ) - (l + 1 : ℝ)) := by
    rw [div_lt_div_iff₀ hcard_pos hgap_pos]
    exact mul_lt_mul_of_pos_left (sub_lt_self _ (by positivity)) (by positivity)
  have hcommon_lower :
      (α : ℝ) - (l + 1 : ℝ) / S'.card ≤ mu_set μ common := by
    apply sub_le_iff_le_add.mpr
    calc
      (α : ℝ) = ((S'.card : ℝ) * (α : ℝ)) / S'.card := by
        rw [mul_div_cancel_left₀ _ hcard_pos.ne']
      _ ≤ ((S'.card : ℝ) * mu_set μ common + (l + 1 : ℝ)) / S'.card :=
        div_le_div_of_nonneg_right hcore hcard_pos.le
      _ = mu_set μ common + (l + 1 : ℝ) / S'.card := by
        rw [add_div, mul_div_cancel_left₀ _ hcard_pos.ne']
  exact lt_of_lt_of_le (sub_lt_sub_left hfraction _) hcommon_lower

/-- Lemma 7.6 in [BCIKS20].
This is the "integral-weight" strengthening of the list-agreement-on-a-curve =>
correlated-agreement bound.

We have two lists of functions `u, v : Fin (l + 2) → ι → F`. From these lists we
form the bivariate curve evaluations. As in Lemma 7.5, code membership is not
needed for this combinatorial strengthening.

* `w x z = Curve.polynomialCurveEval u z x`,
* `wtilde x z = Curve.polynomialCurveEval v z x`.

The domain `ι` is finite and is equipped with a weighted measure `μ`, where each
weight `μ i` is a rational with common denominator `M`. Let `S' ⊆ F` be a set of
field points with
* `S'.card > l + 1`, and
* `S'.card ≥ (M * Fintype.card ι + 1) * (l + 1)`.

Assume that for every `z ∈ S'` the µ-weighted agreement between `w · z` and
`wtilde · z` is at least `α`. Then the µ-measure of the set of points where all
coordinates agree, i.e. where `u i x = v i x` for every `i`, is at least `α`:

`mu_set μ {x | ∀ i, u i x = v i x} ≥ α`. -/
lemma sufficiently_large_list_agreement_on_curve_implies_correlated_agreement
    {l : ℕ} {u : Fin (l + 2) → ι → F}
    {μ : ι → Set.Icc (0 : ℚ) 1}
    {α : ℝ≥0}
    {M : ℕ}
    (hμ : ∀ i, ∃ n : ℤ, (μ i).1 = (n : ℚ) / (M : ℚ))
    {v : Fin (l + 2) → ι → F}
    {S' : Finset F}
    (hS'_card : S'.card > l + 1)
    (hS'_card₁ : S'.card ≥ (M * Fintype.card ι + 1) * (l + 1)) :
    letI w (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) u z x
    letI wtilde (x : ι) (z : F) : F := Curve.polynomialCurveEval (F := F) (A := F) v z x
    (hS'_agree : ∀ z ∈ S', agree μ (w · z) (wtilde · z) ≥ α) →
    mu_set μ { x : ι | ∀ i, u i x = v i x } ≥ α := by
  dsimp only
  classical
  intro hS'_agree
  let w (x : ι) (z : F) : F := Curve.polynomialCurveEval u z x
  let wtilde (x : ι) (z : F) : F := Curve.polynomialCurveEval v z x
  let values : Finset ℝ := S'.image fun z => agree μ (w · z) (wtilde · z)
  have hS'_nonempty : S'.Nonempty := Finset.card_pos.mp (by omega)
  have hvalues_nonempty : values.Nonempty := hS'_nonempty.image _
  let β : ℝ := values.min' hvalues_nonempty
  have hβ_le (z : F) (hz : z ∈ S') : β ≤ agree μ (w · z) (wtilde · z) := by
    exact Finset.min'_le _ _ (Finset.mem_image.mpr ⟨z, hz, rfl⟩)
  have hαβ : (α : ℝ) ≤ β := by
    apply Finset.le_min'
    intro y hy
    rcases Finset.mem_image.mp hy with ⟨z, hz, rfl⟩
    exact hS'_agree z hz
  have hβ_nonneg : 0 ≤ β := le_trans α.coe_nonneg hαβ
  let βnn : ℝ≥0 := ⟨β, hβ_nonneg⟩
  have hcurve_bound :
      mu_set μ {x : ι | ∀ i, u i x = v i x} >
        β - (l + 1 : ℝ) / ((S'.card : ℝ) - (l + 1 : ℝ)) := by
    change mu_set μ {x : ι | ∀ i, u i x = v i x} >
      (βnn : ℝ) - (l + 1 : ℝ) / ((S'.card : ℝ) - (l + 1 : ℝ))
    exact list_agreement_on_curve_implies_correlated_agreement_bound
      (u := u) (v := v) (μ := μ) (α := βnn) hS'_card
      (fun z hz => hβ_le z hz)
  by_contra hnot
  have hmu_lt_alpha :
      mu_set μ {x : ι | ∀ i, u i x = v i x} < (α : ℝ) := by
    simpa only [not_le] using hnot
  have hmu_lt_beta :
      mu_set μ {x : ι | ∀ i, u i x = v i x} < β :=
    lt_of_lt_of_le hmu_lt_alpha hαβ
  rcases Finset.mem_image.mp (Finset.min'_mem values hvalues_nonempty) with
    ⟨zβ, hzβ, hβeq⟩
  change agree μ (w · zβ) (wtilde · zβ) = β at hβeq
  choose numerator hnum using hμ
  have measure_grid (s : Finset ι) :
      ∃ n : ℤ, mu_set μ s = (n : ℝ) / ((M * Fintype.card ι : ℕ) : ℝ) := by
    refine ⟨∑ i ∈ s, numerator i, ?_⟩
    simp only [mu_set]
    simp_rw [hnum]
    push_cast
    rw [← Finset.sum_div]
    field_simp
  have agree_grid (a b : ι → F) :
      ∃ n : ℤ, agree μ a b = (n : ℝ) / ((M * Fintype.card ι : ℕ) : ℝ) := by
    simpa only [agree, mu_set] using measure_grid {i | a i = b i}
  rcases measure_grid {x : ι | ∀ i, u i x = v i x} with ⟨a, ha⟩
  rcases agree_grid (w · zβ) (wtilde · zβ) with ⟨b, hb⟩
  have hM_pos : 0 < M := by
    by_contra hM
    have hMzero : M = 0 := Nat.eq_zero_of_not_pos hM
    have hweights_zero (i : ι) : (μ i).1 = 0 := by
      simpa [hMzero] using hnum i
    have hagree_zero : agree μ (w · zβ) (wtilde · zβ) = 0 := by
      simp [agree, hweights_zero]
    rw [← hβeq, hagree_zero] at hmu_lt_beta
    have hmu_nonneg : 0 ≤ mu_set μ {x : ι | ∀ i, u i x = v i x} := by
      simp [mu_set, hweights_zero]
    linarith
  have hd_pos : (0 : ℝ) < (M * Fintype.card ι : ℕ) := by positivity
  have hab_real : (a : ℝ) < b := by
    rw [ha, ← hβeq, hb] at hmu_lt_beta
    exact (div_lt_div_iff_of_pos_right hd_pos).mp hmu_lt_beta
  have hab : a + 1 ≤ b := by
    have : a < b := by exact_mod_cast hab_real
    omega
  have hgrid_gap :
      1 / ((M * Fintype.card ι : ℕ) : ℝ) ≤
        β - mu_set μ {x : ι | ∀ i, u i x = v i x} := by
    rw [ha, ← hβeq, hb]
    rw [div_sub_div_same]
    apply (div_le_div_iff_of_pos_right hd_pos).2
    have : (1 : ℤ) ≤ b - a := by omega
    exact_mod_cast this
  have hdenom_pos : 0 < (S'.card : ℝ) - (l + 1 : ℝ) := by
    have : (l + 1 : ℝ) < S'.card := by exact_mod_cast hS'_card
    linarith
  have hdenom_large :
      ((M * Fintype.card ι : ℕ) : ℝ) * (l + 1 : ℝ) ≤
        (S'.card : ℝ) - (l + 1 : ℝ) := by
    have hcast :
        (((M * Fintype.card ι + 1) * (l + 1) : ℕ) : ℝ) ≤ S'.card := by
      exact_mod_cast hS'_card₁
    apply le_sub_iff_add_le.mpr
    simpa only [Nat.cast_mul, Nat.cast_add, Nat.cast_one, add_mul, one_mul] using hcast
  have herror_le_grid :
      (l + 1 : ℝ) / ((S'.card : ℝ) - (l + 1 : ℝ)) ≤
        1 / ((M * Fintype.card ι : ℕ) : ℝ) := by
    rw [div_le_div_iff₀ hdenom_pos hd_pos]
    simpa only [one_mul, mul_comm] using hdenom_large
  linarith

end ListAgreementLemmas

end WeightedAgreement

end ProximityGap
